---
name: Security (SCA/Secrets/CodeQL)

on:
  pull_request:
    branches: [develop, staging, main]

jobs:
  gitleaks:
    name: Gitleaks (secrets)
    uses: miguel-lerma/pipelines/.github/workflows/gitleaks.yml@main
    with:
      app_dir: "."

  trivy:
    name: Trivy SCA (deps)
    uses: miguel-lerma/pipelines/.github/workflows/trivy-sca.yml@main
    with:
      app_dir: "."
      severity: "HIGH,CRITICAL"
      ignore_unfixed: "true"
      fail_on_findings: "true"

  codeql:
    name: CodeQL (java)
    uses: miguel-lerma/pipelines/.github/workflows/codeql.yml@main
    with:
      # Si sólo es Java:
      language: "java"

      # Si necesitas compilar manualmente (monorepo, perfiles, etc),
      # activa estas 2 líneas y comenta Autobuild en pipelines, o deja ambas (pipelines respeta run_build):
      # run_build: true
      # build_command: |
      #   sudo apt-get update -y
      #   sudo apt-get install -y maven
      #   mvn -B -DskipTests package
